/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/dialog/ConfirmDialog.vue')['default']
    ElementWrapper: typeof import('./src/components/form/ElementWrapper.vue')['default']
    FrameworkLayout: typeof import('./src/pages/core/framework/AppLayout.vue')['default']
    GridLayout: typeof import('./src/components/form/GridLayout.vue')['default']
    HeaderLayout: typeof import('./src/pages/core/framework/components/HeaderLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LayoutContainer: typeof import('./src/components/form/LayoutContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./src/components/form/SchemaForm.vue')['default']
    SidebarLayout: typeof import('./src/pages/core/framework/components/SidebarLayout.vue')['default']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const ConfirmDialog: (typeof import('./src/components/dialog/ConfirmDialog.vue'))['default']
  const ElementWrapper: (typeof import('./src/components/form/ElementWrapper.vue'))['default']
  const FrameworkLayout: (typeof import('./src/pages/core/framework/AppLayout.vue'))['default']
  const GridLayout: (typeof import('./src/components/form/GridLayout.vue'))['default']
  const HeaderLayout: (typeof import('./src/pages/core/framework/components/HeaderLayout.vue'))['default']
  const HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
  const IconCommunity: (typeof import('./src/components/icons/IconCommunity.vue'))['default']
  const IconDocumentation: (typeof import('./src/components/icons/IconDocumentation.vue'))['default']
  const IconEcosystem: (typeof import('./src/components/icons/IconEcosystem.vue'))['default']
  const IconSupport: (typeof import('./src/components/icons/IconSupport.vue'))['default']
  const IconTooling: (typeof import('./src/components/icons/IconTooling.vue'))['default']
  const LayoutContainer: (typeof import('./src/components/form/LayoutContainer.vue'))['default']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const SchemaForm: (typeof import('./src/components/form/SchemaForm.vue'))['default']
  const SidebarLayout: (typeof import('./src/pages/core/framework/components/SidebarLayout.vue'))['default']
  const TConfigProvider: (typeof import('tdesign-vue-next'))['ConfigProvider']
  const TheWelcome: (typeof import('./src/components/TheWelcome.vue'))['default']
  const TMenu: (typeof import('tdesign-vue-next'))['Menu']
  const WelcomeItem: (typeof import('./src/components/WelcomeItem.vue'))['default']
}
